image: microsoft/dotnet:latest

stages:
    - build
    - test
    - publish

before_script:
    - apt-get update
    - apt-get install nuget -y
    - nuget restore

build:
    stage: build
    script:
        - dotnet build

test:
    stage: test
    script:
    - dotnet test PerformanceRecorderTest/PerformanceRecorderTest.csproj

example:
    stage: test
    script:
    - dotnet run --project ExampleApplication/ExampleApplication.csproj

publish:
    stage: publish
    script:
    - dotnet build
    - dotnet pack ./PerformanceRecorder/PerformanceRecorder.csproj --configuration Release
