image: microsoft/dotnet:latest

stages:
    - build
    - test

before_script:
    - apt-get update
    - apt-get install nuget -y
    - nuget restore

package:
    stage: build
    script:
    - chmod +x BuildTools/*.sh
    - ./BuildTools/Build.sh
    artifacts:
      paths:
      - PerformanceRecorder/bin/Release/*.nupkg
      expire_in: 1 day

test:
    stage: test
    script:
    - dotnet test PerformanceRecorderTest/PerformanceRecorderTest.csproj

example:
    stage: test
    script:
    - dotnet run --project ExampleApplication/ExampleApplication.csproj

