stages:
    - docs
    - build
    - test

.dotnet_template:
    image: microsoft/dotnet:latest
    before_script:
    - apt-get update
    - apt-get install nuget build-essential -y

pages:
    stage: docs
    image: registry.gitlab.com/pages/hugo/hugo:latest
    script:
    - cd docs
    - hugo
    - mv public/ ../public
    artifacts:
      paths:
      - public/
    only:
    - develop

package:
    stage: build
    extends: .dotnet_template
    script:
    - make updateVersion
    - make build
    artifacts:
      paths:
      - PerformanceRecorder/bin/Release/*.nupkg
      expire_in: 1 day

test:
    stage: test
    extends: .dotnet_template
    script:
    - 'dotnet test PerformanceRecorderTest/PerformanceRecorderTest.csproj --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
    artifacts:
      reports:
        junit:
        - ./**/*test-result.xml

example:
    stage: test
    extends: .dotnet_template
    script:
    - dotnet run --project ExampleApplication/ExampleApplication.csproj

