image: mcr.microsoft.com/dotnet/sdk2.1

stages:
    - build
    - test

before_script:
    - apt-get update
    - apt-get install nuget build-essential -y
    - nuget restore

package:
    stage: build
    script:
    - make updateVersion
    - make build
    artifacts:
      paths:
      - PerformanceRecorder/bin/Release/*.nupkg
      expire_in: 1 day

test:
    stage: test
    script:
    - 'dotnet test PerformanceRecorderTest/PerformanceRecorderTest.csproj --test-adapter-path:. --logger:"junit;LogFilePath=..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"'
    artifacts:
      reports:
        junit:
        - ./**/*test-result.xml

example:
    stage: test
    script:
    - dotnet run --project ExampleApplication/ExampleApplication.csproj
